version: 2
updates:
  - package-ecosystem: "go"
    directory: "/"
    schedule:
#      interval: "weekly" # Options: daily, weekly, monthly
      interval: "daily"
#    ignore:
#      - dependency-name: "some-package" # Optional: To ignore specific packages
#        versions: ["1.x"] # Optional: Ignore specific versions
